project:
  type: website

website:
  title: "Esther Chemnitz"
  navbar: 
    favicon: logo.png
    twitter-card: true
    site-url: https://example.com
      
    left:
      - href: index.qmd #the reference for the link
        text: Home #this is the name for the link
      - about.qmd
      - projects.qmd
      
    tools:
      - icon: twitter
        href: https://twitter.com
      - icon: github
        menu:
          - text: Source Code
            url:  https://code.com
          - text: Report a Bug
            url:  https://bugs.com

format:
  html:
    theme: lux
    css: styles.css
    toc: true

editor: visual

